_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": batch/batch_step
              "6":
                - 3
              "7": []
        python_version: 3.9.19
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 7
                - 16
                - 23
                - 38
                - 55
            "4": 3.9.19
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
activation_1:
    value: relu
activation_2:
    value: relu
batch_size:
    value: 64
dropout:
    value: 0.2
epochs:
    value: 50
layer_1:
    value: 64
layer_2:
    value: 128
learning_rate:
    value: 0.0005
sequence_length:
    value: 6
